language: node_js
node_js:
- node
cache: npm
script: npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: main
before_install:
- openssl aes-256-cbc -K $encrypted_bea0181439c1_key -iv $encrypted_bea0181439c1_iv
  -in git_deploy_key.enc -out /tmp/git_deploy_key -d
- chmod 600 /tmp/git_deploy_key
